#
# OSRailway CircleCI 2.1 Configuration
# (based on https://github.com/dominikbraun/espresso/blob/master/.circleci/config.yml)
#
version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.14
        environment:
          CGO_ENABLED: 0
          G111MODULE: "on"

jobs:
  osrailway-control-build-releases:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - dependency-cache-v1-{{ .Branch }}-
            - dependency-cache-v1-
            - repository-cache-v1-{{ .Branch }}-{{ .Revision }}
            - repository-cache-v1-{{ .Branch }}-
            - repository-cache-v1-
      - run: go mod download
      - save_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: repository-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: mkdir -p /tmp/artifacts
      - run: go generate
      - run:
          name: Build and pack Espresso for Linux
          command: |
            GOOS=linux GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
            -o .target/osrailway-control main.go
            cp .target/osrailway-control osrailway-control
            tar -czf /tmp/artifacts/osrailway-control-linux-amd64.tar.gz osrailway-control
      - run:
          name: Build and pack Espresso for macOS
          command: |
            GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o .target/osrailway-control main.go
            cp .target/osrailway-control osrailway-control
            tar -czf /tmp/artifacts/osrailway-control-macos-amd64.tar.gz osrailway-control
      - run:
          name: Build and pack Espresso for Windows
          command: |
            GOOS=windows GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o .target/osrailway-control.exe main.go
            cp .target/osrailway-control.exe osrailway-control.exe
            zip /tmp/artifacts/osrailway-control-windows-amd64.zip osrailway-control.exe
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - osrailway-control-linux-amd64.tar.gz
            - osrailway-control-macos-amd64.tar.gz
            - osrailway-control-windows-amd64.zip

  osrailway-control-release-gh:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run: mkdir artifacts && cp /tmp/artifacts/* artifacts/
      - run:
          name: Publish GitHub release
          command: |
            ghr -t "${GITHUB_TOKEN}" \
                -u "${CIRCLE_PROJECT_USERNAME}" \
                -r "${CIRCLE_PROJECT_REPONAME}" \
                -c "${CIRCLE_SHA1}" \
                -delete "${CIRCLE_TAG}" \
                artifacts/

workflows:
  version: 2
  osrailway-control-ci:
    jobs:
      - osrailway-control-build-releases:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - osrailway-control-release-gh:
          requires:
            - osrailway-control-build-releases
          filters:
            tags:
              only: /.*/